CREATE TABLE IF NOT EXISTS users (
  id text PRIMARY KEY NOT NULL,
  full_name text NOT NULL,
  email text NOT NULL,
  password_hash text,
  role text DEFAULT 'team_member' NOT NULL,
  team text DEFAULT 'Product' NOT NULL,
  job_title text DEFAULT 'Team Member' NOT NULL,
  status text DEFAULT 'active' NOT NULL,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON users (email);

CREATE TABLE IF NOT EXISTS projects (
  id text PRIMARY KEY NOT NULL,
  name text NOT NULL,
  description text DEFAULT '' NOT NULL,
  owner_id text REFERENCES users(id) ON UPDATE no action ON DELETE no action,
  team text DEFAULT 'Product' NOT NULL,
  status text DEFAULT 'active' NOT NULL,
  start_date text,
  end_date text,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS projects_name_unique ON projects (name);

CREATE TABLE IF NOT EXISTS reports (
  id text PRIMARY KEY NOT NULL,
  user_id text NOT NULL REFERENCES users(id) ON UPDATE no action ON DELETE no action,
  report_type text NOT NULL,
  project_id text NOT NULL REFERENCES projects(id) ON UPDATE no action ON DELETE no action,
  report_date text,
  period_label text NOT NULL,
  completed_work text NOT NULL,
  work_in_progress text DEFAULT '' NOT NULL,
  planned_work text DEFAULT '' NOT NULL,
  planned_work_items text,
  blockers text DEFAULT '' NOT NULL,
  support_needed text DEFAULT '' NOT NULL,
  decisions_needed text DEFAULT '' NOT NULL,
  documentation_links text DEFAULT '' NOT NULL,
  priority text DEFAULT 'medium' NOT NULL,
  status text DEFAULT 'in_progress' NOT NULL,
  additional_notes text DEFAULT '' NOT NULL,
  submitted_at timestamptz,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
  id text PRIMARY KEY NOT NULL,
  report_id text NOT NULL REFERENCES reports(id) ON UPDATE no action ON DELETE no action,
  user_id text NOT NULL REFERENCES users(id) ON UPDATE no action ON DELETE no action,
  comment text NOT NULL,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  user_id text NOT NULL REFERENCES users(id) ON UPDATE no action ON DELETE no action,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  details text DEFAULT '' NOT NULL,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS invitations (
  id text PRIMARY KEY NOT NULL,
  token text NOT NULL,
  email text NOT NULL,
  role text DEFAULT 'team_member' NOT NULL,
  team text DEFAULT 'Product' NOT NULL,
  job_title text DEFAULT 'Team Member' NOT NULL,
  invited_by text NOT NULL REFERENCES users(id) ON UPDATE no action ON DELETE no action,
  status text DEFAULT 'pending' NOT NULL,
  expires_at timestamptz NOT NULL,
  accepted_at timestamptz,
  accepted_by text REFERENCES users(id) ON UPDATE no action ON DELETE no action,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS invitations_token_unique ON invitations (token);
CREATE INDEX IF NOT EXISTS idx_invitations_email_status ON invitations (email, status);

CREATE TABLE IF NOT EXISTS sessions (
  id text PRIMARY KEY NOT NULL,
  user_id text NOT NULL REFERENCES users(id) ON UPDATE no action ON DELETE cascade,
  token text NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS sessions_token_unique ON sessions (token);

CREATE TABLE IF NOT EXISTS workspace_settings (
  key text PRIMARY KEY NOT NULL,
  value text NOT NULL,
  updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);
